package com.simplyapp.pixelskylivewallpaper.utils

import android.graphics.Color
import com.simplyapp.pixelskylivewallpaper.utils.StarsPrefsHelper.Companion.PREF_COLOUR_CUSTOM_1
import com.simplyapp.pixelskylivewallpaper.utils.StarsPrefsHelper.Companion.PREF_COLOUR_CUSTOM_2
import com.simplyapp.pixelskylivewallpaper.utils.StarsPrefsHelper.Companion.PREF_COLOUR_CUSTOM_3
import com.simplyapp.pixelskylivewallpaper.utils.StarsPrefsHelper.Companion.PREF_COLOUR_CUSTOM_4

enum class Colour constructor(val customId: String?, vararg val colours: Int) {
    BLUE(null,
            Color.parseColor("#239dce"),
            Color.parseColor("#2192bc"),
            Color.parseColor("#2196c2"),
            Color.parseColor("#2298c6"),
            Color.parseColor("#1f8eb9"),
            Color.parseColor("#24a0d3"),
            Color.parseColor("#229dc9"),
            Color.parseColor("#2191bf"),
            Color.parseColor("#2298c6"),
            Color.parseColor("#1b7ba3"),
            Color.parseColor("#59c2ee"),
            Color.parseColor("#0c88f4"),
            Color.parseColor("#1a76e1")),
    GREEN(null,
            Color.parseColor("#81C784"),
            Color.parseColor("#43A047"),
            Color.parseColor("#2E7D32"),
            Color.parseColor("#1B5E20"),
            Color.parseColor("#6D4C41"),
            Color.parseColor("#7CB342"),
            Color.parseColor("#558B2F")),
    GREY(null,
            Color.parseColor("#CCCCCC"),
            Color.parseColor("#FFFFFF"),
            Color.parseColor("#000000"),
            Color.parseColor("#838383"),
            Color.parseColor("#AAAAAA"),
            Color.parseColor("#333333"),
            Color.parseColor("#555555")),
    PURPLE(null,
            Color.parseColor("#BA68C8"),
            Color.parseColor("#9C27B0"),
            Color.parseColor("#7B1FA2"),
            Color.parseColor("#76008A"),
            Color.parseColor("#6A1B9A"),
            Color.parseColor("#4A148C"),
            Color.parseColor("#6D2D78"),
            Color.parseColor("#AA00FF")),
    RED(null,
            Color.parseColor("#FF5733"),
            Color.parseColor("#F13C15"),
            Color.parseColor("#BA3316"),
            Color.parseColor("#911B01"),
            Color.parseColor("#EC7358"),
            Color.parseColor("#ED1B0E"),
            Color.parseColor("#FF9F0C"),
            Color.parseColor("#870923")),
    NEXUS(null,
            Color.parseColor("#ffffff"),
            Color.parseColor("#25ADFF"),
            Color.parseColor("#FFC100"),
            Color.parseColor("#FF3800")),
    PINK(null,
            Color.parseColor("#F62DAE"),
            Color.parseColor("#E0299F"),
            Color.parseColor("#B91793"),
            Color.parseColor("#A4036F"),
            Color.parseColor("#D30C7B")),
    PASTEL(null,
            Color.parseColor("#e8ebea"),
            Color.parseColor("#dab6c8"),
            Color.parseColor("#a6dcee"),
            Color.parseColor("#5389a6"),
            Color.parseColor("#00040e")),
    SPECTRUM(null,
            Color.parseColor("#9400D3"),
            Color.parseColor("#4B0082"),
            Color.parseColor("#0000FF"),
            Color.parseColor("#00FF00"),
            Color.parseColor("#FFFF00"),
            Color.parseColor("#FF7F00"),
            Color.parseColor("#FF0000")
    ),
    DARK(null,
            Color.parseColor("#10102c"),
            Color.parseColor("#342c5c"),
            Color.parseColor("#67647d"),
            Color.parseColor("#272d50"),
            Color.parseColor("#bdc7d8")
    ),
    GOLD(null,
            Color.parseColor("#ffd483"),
            Color.parseColor("#ffda68"),
            Color.parseColor("#a98c46"),
            Color.parseColor("#fff381"),
            Color.parseColor("#b4a14f")
    ),
    RETRO(null,
            Color.parseColor("#c8783f"),
            Color.parseColor("#e1b878"),
            Color.parseColor("#75acc0"),
            Color.parseColor("#66202a")),
    CUSTOM1(PREF_COLOUR_CUSTOM_1),
    CUSTOM2(PREF_COLOUR_CUSTOM_2),
    CUSTOM3(PREF_COLOUR_CUSTOM_3),
    CUSTOM4(PREF_COLOUR_CUSTOM_4);

}
